name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      LOCATION: asia-northeast1
      PROJECT_ID: ardent-curve-457502-d9
      REPOSITORY: notely-ar-repo
      IMAGE: notely
      TAG: latest
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up goose
        uses: mscno/setup-goose@v1

      - name: Migrate database
        working-directory: ./sql/schema
        run: goose turso $DATABASE_URL up
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
